[package]
name = "sudoku"
version = "0.14.0"
authors = ["Martin-Louis Bright <mlbright@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
rand = "0.7.3"
arrayvec = "0.7.2"
array-macro = "2.1.5"